import argparse

def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("--train_path", type=str,default="./data/cellxgene/data_scbank/train3/train3_mini_data_first_half.parquet",help='The name of the data source (currently support "scvi" datasets), or the '"path to the data file.")
    parser.add_argument("--test_path", type=str,default="./data/cellxgene/data_scbank/test3/test3_mini_data.parquet")
    parser.add_argument("--valid_path", type=str,default="./data/cellxgene/data_scbank/test3/test3_mini_data.parquet")
    parser.add_argument("--train_style", type=str,default="mini3")
    parser.add_argument("-s","--save-dir",type=str,default="",help="The directory to save the trained model and the results.",)
    parser.add_argument("--load_model",type=str,default=None,help="The directory containing the model and configs to load and continue training.")
    # settings for data
    parser.add_argument("--pad-token",type=str,default="<pad>",help="The token to use for padding. Default is <pad>.")
    parser.add_argument("--input-emb-style",type=str,choices=["continuous"],default="continuous",help="The style of the input embedding. Default is continuous.")
    parser.add_argument("--cell_emb_style",type=str,choices=["cls", "avg-pool"],default="cls",help="The style of the input embedding. Default is continuous.")
    parser.add_argument("--n-bins",type=int,default=51,help="The number of bins to use for the binned input style. Default is 51.")
    parser.add_argument("--train_maxseq",type=int,default=512,help="The maximum length of the sequence. Default is 1000. The actual used max length would be the minimum of this value and the length of the longest sequence in the data.")
    parser.add_argument("--test_maxseq",type=int,default=512)
    parser.add_argument("--mask_ratio",type=float,default=0.40,help="The ratio of masked values in the training data. Default is 0.40. This value will be ignored if --training-tasks is set to gen or both.")
    parser.add_argument("--eval_mask_ratio",type=float,default=0.40,help="The ratio of masked values in the training data. Default is 0.40. This value will be ignored if --training-tasks is set to gen or both.")
    parser.add_argument("--vocab-path",type=str,default="vocab.json",help="Path to the vocabulary file.")
    # settings for training
    parser.add_argument("--local-rank",type=int,default=-1,help="The local rank of the process for using the torch.distributed.launch utility. Will be -1 if not running in distributed model.")
    parser.add_argument("--batch_size",type=int,default=128,help="The batch size for training. Default is 64.")
    parser.add_argument("--epochs",type=int,default=5,help="The number of epochs for training.")
    parser.add_argument("--lr",type=float,default=5e-4,help="The learning rate for training. Default is 1e-3.")
    parser.add_argument("--debug",action="store_true",help="break train and eval")
    parser.add_argument("--only_eval",action="store_true",help="no training")
    parser.add_argument("--resume",action="store_true")
    parser.add_argument("--fp16",action="store_true",help="Whether to train in automatic mixed precision. Default is False.")
    parser.add_argument("--nlayers",type=int,default=6,help="The number of layers for the transformer. Default is 4.")
    parser.add_argument("--nheads",type=int,default=8,help="The number of heads for the transformer. Default is 4.")
    parser.add_argument("--embsize",type=int,default=256,help="The embedding size for the transformer. Default is 64.")
    parser.add_argument("--dict_size",type=int,default=256,help="The embedding size for the transformer. Default is 64.")
    parser.add_argument("--dropout",type=float,default=0.15,help="The dropout rate. Default is 0.15.")
    parser.add_argument("--base_ratio",type=float,default=0.5)
    parser.add_argument("--exclude_fix",nargs='+',default=[0,0,0])
    parser.add_argument("--base_ratio_dataset",type=float,default=0.5)
    parser.add_argument("--num_workers",type=int,default=6)
    parser.add_argument("--save_interval",type=int,default=1)
    parser.add_argument("--max_clamp",type=int,default=20)
    parser.add_argument("--mask_value",type=int,default=-1)
    parser.add_argument("--pad_value",type=int,default=0)
    parser.add_argument("--cls_value",type=int,default=0)
    parser.add_argument("--num_stages",type=int,default=3)
    parser.add_argument("--select_idxnum",type=int,default=200)
    parser.add_argument("--keep_num",type=int,default=20)
    parser.add_argument("--min_diff",type=int,default=50,help="for add the dominate IDs (if appear in other sets, the distance should over than a value)")
    parser.add_argument("--seed",type=int,default=0)
    parser.add_argument("--replay_num",type=int,default=10)
    parser.add_argument("--keep_rank1",type=int,default=20)
    parser.add_argument("--keep_rank2",type=int,default=100)
    parser.add_argument("--distill_coef",type=float,default=1.0)
    parser.add_argument("--distill_mode",type=str,default="feature")
    # settings for logging
    parser.add_argument("--log-interval",type=int,default=500,help="The interval for logging. Default is 100.")
    parser.add_argument("--warmup_iters",type=int,default=5000,help="for warmup. Default is 10000.")
    parser.add_argument("--preprocess_mode",type=str,default="none")
    parser.add_argument("--impscore_path",type=str,default="analysis/imp_genes4cls.torch")
    parser.add_argument("--model_structure",type=str,default="transformer")
    parser.add_argument("--use_weighted_sampling",action="store_true")
    parser.add_argument("--use_weighted_loss",action="store_true")
    parser.add_argument("--only1stage",action="store_true")
    parser.add_argument("--incre_only",action="store_true")
    parser.add_argument("--keep_base_id",action="store_true")
    parser.add_argument("--notavg",action="store_true")
    parser.add_argument("--skip_stage0",action="store_true")
    parser.add_argument("--distribute_impid",action="store_true")
    parser.add_argument("--excludefin",action="store_true")
    parser.add_argument('--load_dir', type=str, default="", help='Directory to load base models and datasets configurations')
    parser.add_argument("--add_note",type=str,default="")
    parser.add_argument("--load_token_name",type=str,default="")
    parser.add_argument("--filter_names", nargs='+',
                        default=[ "XXX"],
                        # , "ircolitis", "myasthenia", "lupus",
                        #          "scfoundation", "scanorama", "dengue", "leptomeningeal"],
                        help="List of filter names to process.")
    args = parser.parse_args()
    return args